baseURL: "https://ananya-khare.github.io"
languageCode: "en-us"
title: "Ananya Khare"
theme: portfolio

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Ananya Khare"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ananya"
    content: "I am a final year B.Tech - CSE student, passionate about Software Development and Cybersecurity"
    image: /images/Ananya.jpg
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/ananya-khare
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ananya-khare-064867190/
  # About
  about:
    enable: true
    title: "About Me"
    content: |-
      I am a student from India. I have a background in Computer Science and Cybersecurity. I am looking to expand my knowledge in these fields and for work opportunities that give me a chance to make the existing and upcoming systems more security inclusive.
    
    skills:
      enable: true
      title: "Here are a few technologies I've worked with"
      items:
        - "PROGRAMMING LANGUAGES : Python, Java, Javascript"
        - "DATABASES : Mongodb, Oracle, PostgreSQL"
        - "FRAMEWORKS : Flask, Django, React, Express, Angular"
        - "WEB DEV : HTML, CSS, Bootstrap, Tailwind"
        - "SECURITY AND NETWORKING : Wireshark, Burp Suite" 

  
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Technology in Computer Science"
        school:
          name: "NIIT University, Rajathan"
        date: "2019 - 2023"
        GPA: "8.64"
      - title: "12th CBSE Boards"
        school:
          name: "Sir Padampat Singhania Education Centre, Kanpur"
        date: "2019"
        PERCENTAGE: "94%"

  # projects
  projects:
    enable: true
    items:
      - title: NUSec
        content: A browser based web application scanner that scans for more than 100 vulnerabilities. 
        image: /images/NUSEC.png
        badges:
          - "Flask"
          - "FastAPI"
          - "Tailwind CSS"
          - "Flowbite"
          - "Docker"
        links:
          - icon: fab fa-github
            url: https://github.com/ananya-khare/R-D---NUSEC

      - title: Kissan Connect
        content: An informational blog for farmers and an e-commerce platform for them to sell their produce.
        image: /images/KisanKonnect.jpg
        badges:
          - "HTML"
          - "CSS"
          - "Bootstrap"
          - "React"

      - title: HoverFly
        content: Drone based gas leak and rust detection system for cooking gas pipelines. 
        image: /images/hoverfly.jpg
        badges:
          - "Python"
          - "Open CV"

  #Contact
  contact:
    enable: true
    content: My inbox is always open. I’ll try my best to get back to you! 
    email: ananyakhare97@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/ananya-khare
      linkedin: https://www.linkedin.com/in/ananya-khare-064867190/